# Generated by Django 4.0.2 on 2022-02-14 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
        ('receita', '0002_rename_rendimenrto_receita_rendimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='pessoas',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoas'),
            preserve_default=False,
        ),
    ]
