# Generated by Django 4.0.2 on 2022-02-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0003_receita_pessoas'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
